# Generated by Django 4.0.4 on 2022-06-15 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('like_from', models.ManyToManyField(help_text='いいねしたユーザー', related_name='like_from', to=settings.AUTH_USER_MODEL)),
                ('like_to', models.ForeignKey(help_text='いいねする投稿', on_delete=django.db.models.deletion.CASCADE, related_name='like_to', to='api.post', verbose_name='投稿ID')),
            ],
        ),
    ]
