# Generated by Django 4.0.4 on 2022-06-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_liked_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_from',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_to',
        ),
        migrations.AddField(
            model_name='like',
            name='like_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='api.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likd_by', to='api.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(through='api.Like', to='api.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(through='api.Like', to='api.post'),
        ),
    ]
